CREATE TABLE IF NOT EXISTS movie(
movieID INTEGER UNIQUE NOT NULL PRIMARY KEY,
title VARCHAR(50),
genre VARCHAR(20),
stock INTEGER,
avgRating DECIMAL (1,1));

CREATE TABLE IF NOT EXISTS customer(
username VARCHAR(10) UNIQUE NOT NULL PRIMARY KEY,
password VARCHAR(50),
name VARCHAR(50),
age INTEGER);

CREATE TABLE IF NOT EXISTS rental(
username VARCHAR(10) NOT NULL,
movieID INTEGER NOT NULL, 
dueDate VARCHAR(50),
PRIMARY KEY (username, movieID));

CREATE TABLE IF NOT EXISTS rating(
username VARCHAR(10) NOT NULL,
movieID INTEGER NOT NULL,
rating DECIMAL(1,1),
PRIMARY KEY (username, movieID));